Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.


#include <stdio.h>
#include <stdlib.h>

int main()
{
    int fib1=0,fib2=1,fib3=0,counter=0;
    while(counter<10)
    {
        fib3=fib1+fib2;
        fib1=fib2;
        fib2=fib3;
        counter+=1;
        printf("%d.Fibonacci numbers %d\n",counter,fib3);
    }
    return 0;
}
